# =================================================== Overview =========================================================
# pip3.12 install -e .
[project]
name = "Analog-Automagic-Layout"
version = "2.0.0"
description = "Generates a Magic VLSI layout from an Xschem schematic"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE" }
requires-python = ">=3.10"
authors = [
    { name = "Bjørn K.T. Solheim", email = "bjorn_solheim@hotmail.no" },
    { name = "Leidulv Tønnesland", email = "leidulv.tonnesland@gmail.com" },
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

# ===================================================== Configs ========================================================

# Linear optimization config options
# -> Alpha - Constant for weighing the importance of total Manhattan distance between components in the objective function
# -> Beta - Constant for weighing the importance of perimeter along the x-axis in the objective function
# -> Theta - Constant for weighing the importance of perimeter along the y-axis in the objective function
# -> Unit_width, Unit_height - Unit width and height are intervals of allowable placements along the x- and y-axis
# -> Offset_x, Offset_y - Minimum offset along the x- and y-axis between components that can not overlap
# -> Mirror - Boolean used for debugging. Turns on or off the mirroring constraint
# -> Run - Boolean used for debugging. Turns on or off the execution of linear optimization
# -> Stop_tolerance - MIP gap threshold percentage for when to stop searching with respect to the relative difference
#                     between primal and dual solutions

[linear_optimization]
UNIT_HEIGHT = 100
UNIT_WIDTH = 64
OFFSET_X = 184
OFFSET_Y = 700
ALPHA = 0.001
BETA = 100
THETA = 5
TIME_LIMIT = 2
MIRROR = true
RUN = true

STOP_TOLERANCE = 0.05
SOLVER_MSG = true

# Magic layout creator config options
# -> Technology - defines which PDK technology we are targeting
# -> Metal layers - defines the metal layers that can be route in (ascending order)
# -> Via map - defines the via layers we can route in (ascending order)
# -> Via padding - defines how much padding in units of 1e-8m should be added around all vias

[magic_layout_creator]
TECHNOLOGY = 'sky130A'
METAL_LAYERS = ['locali', 'm1', 'm2', 'm3', 'm4']
VIA_MAP = {"locali-m1" = "viali", "m1-m2" = "via1", "m2-m3" = "via2", "m3-m4" = "via3"}
VIA_PADDING = 7

# Trace generator config options
# -> Init rail ring offset x/y - offset from cells defined bounding box
# -> rail ring offset - distance from the outside of one ring to the outside of the next
# -> rail width - width of the rails

[trace_generator]
INIT_RAIL_RING_OFFSET_Y = 350
INIT_RAIL_RING_OFFSET_X = 1500
RAIL_RING_OFFSET = 150
RAIL_RING_WIDTH = 100

# Generate grid config options
# -> Grid size - area the components have to fit within
# -> Scale factor - shrink factor for routing space representation
# -> Via minimum distance - minimum offset between via points
# -> Trace width - width of traces
# -> Grid leeway x/y - extra space outside of component placement for additional routing space

[generate_grid]
GRID_SIZE = 4500
SCALE_FACTOR =16
TRACE_WIDTH = 30
VIA_MINIMUM_DISTANCE = 20
GRID_LEEWAY_X = 1000
GRID_LEEWAY_Y = 500
# Astar initiator config options
# -> Run multiple astar - allows a star to be executed with each goal node as initial position to find the shortest path
# -> Custom net order - allows predefined order of nets in a star execution
# -> Net order - the predefined order

[a_star_initiator]
RUN_MULTIPLE_ASTAR = true
CUSTOM_NET_ORDER = true
NET_ORDER1 = ["net3","VO", "VIN", "VIP", "I_BIAS", "net4", "net1", "net2"]
NET_ORDER = ["VIN", "net2", "VO", "net1", "I_BIAS", "net3", "VIP", "net4"]
test_order2 = ["net3","VIP","VO","net1","I_BIAS","VIN","net4","net2"]
test_order3 = ["VIP","VO","VIN","net1","net4","net2","net3","I_BIAS"]

[DRAW_RESULT]
FILE_NAME = 'Temporary_check'
