# =================================================== Overview =========================================================
# pip3.12 install -e .
[project]
name = "Analog-Automagic-Layout"
version = "2.0.0"
description = "Generates a Magic VLSI layout from an Xschem schematic"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE" }
requires-python = ">=3.10"
authors = [
    { name = "Bjørn K.T. Solheim", email = "bjorn_solheim@hotmail.no" },
    { name = "Leidulv Tønnesland", email = "leidulv.tonnesland@gmail.com" },
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

# ===================================================== Configs ========================================================
[linear_optimization]
UNIT_HEIGHT = 100
UNIT_WIDTH = 64
OFFSET_X = 184
OFFSET_Y = 128
ALPHA = 0.001
BETA = 100
THETA = 1
MIRROR = true
RUN = true
EARLY_STOP_TOLERANCE_GAP = 0.05



