import os
import time
import sh


class SPICEparser:

    def __init__(self, project_name: str, project_dir: str):
        self.project_name = project_name
        self.project_dir = project_dir
        self.spice_file_content = list()
        self.components = dict()

        self.parse()


    def _generate_spice_file_for_schematic(self):


        # Path to the folder that will be generated by the make command
        #folder_path = os.path.expanduser(
        #    f"{self.project_dir}work/xsch")

        # Remove the folder if it already exists
        #if os.path.exists(folder_path):
        #    print(f"[INFO]: Removing old folder at {folder_path}")
        #    shutil.rmtree(folder_path)

        # Change directory to '/work'
        #os.chdir(os.path.expanduser(f"{self.project_dir}work/"))

        # Directory where the command needs to be executed
        work_dir = f"{self.project_name}work"

        # Change to the specified directory and run the command
        try:
            with sh.cd(work_dir):
                sh.make("xsch")

                print("[INFO]: SPICE file generated from schematic")
        except sh.ErrorReturnCode as e:
            print(f"[ERROR]: 'make xsch' command failed with: {e.stderr.decode()}")





    def _read_spice_file(self):
        try:
            spice_file_path = os.path.expanduser(f"{self.project_dir}work/xsch/{self.project_name}.spice")

            # Copy each line of the file into a list
            with open(spice_file_path,"r") as spice_file:
                for line in spice_file:
                    self.spice_file_content.append(line)

        except FileNotFoundError:
            print(f"Error: The file '{self.project_dir}work/xsch/{self.project_name}.spice' was not found.")


    def parse(self):
        self._generate_spice_file_for_schematic()
        #self._read_spice_file()

        # temp printing
        for index, line in enumerate(self.spice_file_content):
            print(self.spice_file_content[index])






