!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - clip_range
    - 0.2
  - - ent_coef
    - 0.0
  - - gae_lambda
    - 0.95
  - - gamma
    - 0.99
  - - learning_rate
    - 0.0001
  - - max_grad_norm
    - 0.5
  - - n_envs
    - 1
  - - n_epochs
    - 10
  - - n_timesteps
    - 100000.0
  - - normalize
    - true
  - - policy
    - MlpPolicy
  - - vf_coef
    - 0.5
